#!/bin/bash

MAIN_PKGS() {
sudo xbps-install -Syu -u xbps && sudo xbps-install -Syu
sudo xbps-install -Syu xfce4 xfce4-whiskermenu-plugin thunar-archive-plugin tree pulseaudio bluez blueman xfce4-pulseaudio-plugin pavucontrol papirus-icon-theme arc-theme evince torbrowser-launcher gnome-calculator scrot qbittorrent mpv firefox chromium torbrowser-launcher github-cli yt-dlp neofetch ntfs-3g xorg-minimal mesa xorg-fonts network-manager-applet telegram-desktop gvfs-mtp gvfs xz file-roller os-prober vim git xf86-input-libinput 

#model=$(lscpu | grep 'Model name')
#case "$model" in
#    *Intel*) sudo xbps-install -Syu xf86-video-intel ;;
#    *AMD*) sudo xbps-install -Syu xf86-video-amdgpu ;;  
#esac
}



START_SERVICES(){

sudo ln -s /etc/sv/bluetoothd /var/service
sudo ln -s /etc/sv/polkitd /var/service
sudo ln -s /etc/sv/rtkit /var/service
sudo ln -s /etc/sv/elogind /var/service
sudo ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/
sudo xbps-reconfigure -f fontconfig
#sudo echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
#sudo grub-mkconfig -o /boot/grub/grub.cfg

#sudo mkdir /etc/X11/xorg.conf.d
#sudo touch /etc/X11/xorg.conf.d/30-touchpad.conf
#sudo echo '
#Section "InputClass"
#    Identifier "touchpad"
#    Driver "libinput"
#   MatchIsTouchpad "on"
#    Option "Tapping" "on"
#    Option "TappingButtonMap" "lmr"
#EndSection ' >> /etc/X11/xorg.conf.d/30-touchpad.conf


#sudo echo "load-module module-switch-on-connect" >> /etc/pulse/default.pa 
#sudo echo "echo 0 > /sys/class/backlight/amdgpu_bl0/brightness" > /etc/rc.local
#(do not run) sudo xbps-install mesa-vaapi mesa-vdpau
#sudo echo "blacklist nouveau" > /usr/lib/modprobe.d/blacklist.conf
#sudo touch /etc/modprobe.d/nouveau_blacklist.conf 
#sudo echo "blacklist nouveau" > /etc/modprobe.d/nouveau_blacklist.conf
#KE_VERN=$(uname -r | cut -d. -f-2) 
#sudo xbps-reconfigure -f linux${KE_VERN}
}



CNWR_CY() {
cp -r .config .xinitrc .zshrc .fonts /$HOME/ 
fc-cache -fv

}







REBOOT_CASE() { 
clear && /bin/echo -e '\n\n' "\e[1;32mREBOOTING NOW......\e[0m"
sleep 1
clear && /bin/echo -e '\n\n' "\e[1;31mEXITING......\e[0m" 
sudo reboot
}


#runfunctions

MAIN_PKGS 
START_SERVICES
CNWR_CY
REBOOT_CASE
